# @package _global_

Dataset: 2d
datasets: [moon, circle, swiss]
data_root: none
dim: 2
scaling_factor: 7.

# Barycenter
barycenter_weights: [0.333, 0.333, 0.333]

# OT regularization
epsilon: 0.05
n_ipf: 20
start_n_ipf: 0

# device
device: cpu
dataparallel: True
num_workers: 0
pin_memory: False

# global training
n_back_and_return: 0

# training on each edge
mean_match: False
npar: 10000
cache_npar: 1000
num_cache_batches: 10
cache_refresh_stride: 500
ema: False
ema_rate: 0.999
grad_clipping: False
grad_clip: 1.0
batch_size: 4096
num_iter : 10000
lr: 0.0001

# schedule on each edge
num_steps : 50
gamma_min: 0.00001
gamma_space: linspace

# plot and save
plot: True
plot_npar: 5000
plot_freq: ${num_steps}
plot_particle: False
plot_trajectory: False
plot_registration: False
plot_density: True
plot_density_smooth: True
save_stride: 1
log_stride: 50
gif_stride: ${num_iter}

# checkpoints for model
checkpoint_run: True
checkpoints_dir: '../../../../../checkpoints_model/2d_3datasets_epsilon=0.05'

checkpoint_f: "net_f_35_10000.ckpt"
checkpoint_b: "net_b_35_10000.ckpt"

# load some data on the root at the initialisation
data_root_load: False
data_root_path: '../../../../../checkpoints_data/2d_3datasets/data_root_epsilon=0.050.pt'
