# @package _global_

defaults:
  - launcher: local
  - job
  - dataset: 2d_3datasets # see config/dataset/...
  - model: Basic #Basic, UNET
  - tree: Barycenter #Bridge, Barycenter

# data
data_dir: ../../../../../data/

# logging
LOGGER: CSV # NEPTUNE, CSV, NONE
CSV_log_dir: ./

# plots
plot_cache_time: False
plot_level: 1 # number of pictures saved for image datasets, apart from the starting node
paths:
  experiments_dir_name: experiments

# saving dynamics with ODE
plot_ODE: False
schedule_ODE: cosine
#    - cosine: interpolation between Langevin dynamics and probability flow on a cosine schedule (SDE -> ODE)
#    - one: only probability flow
coeff_schedule_ODE: 2
#    - if cosine: strength of the cosine schedule (>0) -> typically 2

# saving dynamics with SDE
plot_SDE: True
schedule_SDE: zero
#    - cosine: Langevin dynamics with decreasing noise on a cosine schedule
#    - binary: Langevin dynamics with decreasing noise on a binary schedule
#    - zero: classic Langevin dynamics
coeff_schedule_SDE: 1
#    - if cosine: strength of the cosine schedule (>0) -> typically 1
#    - if binary: strength of the binary schedule (between 0 and 1) -> typically 0.9

# starting leaf seed
starting_leaf_seed: 0

# penalizing the norm of the drifts during training process
loss_weight: 0.

# predictor/corrector
num_corrector_steps: 1
start_corrector: 1 # number of first iterations without corrector in train_model
test_with_corrector: True # using corrector in test_model
snr: 0.02 # signal-to-noise ratio